sudo: required

language: python

services:
  - docker

before_install:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

script:
  - ./dev docker-build
  - ./dev docker-push