sudo: required

language: generic

branches:
  only:
  - master

services:
  - docker

script:
  - set -e
  - ./dev docker-build
  - ./dev docker-run --local --rounds 10

before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

deploy:
  - ./dev docker-push