#!/bin/bash
set -euf

self="${0}"
workdir="$(dirname "$(realpath "${self}")")"
cd "${workdir}"

case "${1:-}" in
  "fmt")
    set -x
    find . -not -path '*/\.*' -type f -name '*.py' -exec \
      yapf -i --style .style.yapf -p {} '+' || true
    ;;
  "docker-build")
    docker build -t dns-test:latest .
    ;;
  "docker-run")
    docker run --rm -t dns-test:latest ${@:2}
    ;;
  *)
    echo "usage: ${self} <fmt|docker-build|docker-run>"
    ;;
esac
