#!/bin/bash
set -euf

self="${0}"
workdir="$(dirname "${self}")"
cd "${workdir}"

DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-dns-test:latest}"

case "${1:-}" in
  "fmt")
    set -x
    find . -not -path '*/\.*' -type f -name '*.py' -exec \
      yapf -i --style .style.yapf -p -vv {} '+' || true
    ;;
  "docker-build")
    docker build -t "${DOCKER_IMAGE_NAME}" .
    ;;
  "docker-push")
    docker push "${DOCKER_IMAGE_NAME}"
    ;;
  "docker-run")
    docker run --rm -t \
      --user "$(id -u):$(id -g)" \
      -v "${workdir}:/workdir:rw" \
      "${DOCKER_IMAGE_NAME}" ${@:2}
    ;;
  "download-umbrella")
    cd domains
    wget -O- 'http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip' | gunzip >umbrella.csv
    ;;
  *)
    echo "usage: ${self} <fmt|docker-build|docker-run|docker-push|download-umbrella>"
    ;;
esac
